### ISSUE TITLE
Add D10 compatibility so we can uninstall this module

### ISSUE THREAD

**Issue by slaymoore** [rmarsh1ua/grad_migration#10]
https://github.com/uazgraduatecollege/grad_migration/blob/e47c8750fef3bba37949df715b957268616e6e22/gc_migration.info.yml#L3

We need to add `|| ^10` to the line referenced above so we can properly uninstall this module.

Thanks!

**Comment by slaymoore** [comment]
Oops, the [composer.json](https://github.com/uazgraduatecollege/grad_migration/blob/e47c8750fef3bba37949df715b957268616e6e22/composer.json#L6) file needs updated as well.

**Comment by pbarabe** [comment]
Updated branch `site_migr_physcigidp` w/ commit `62489abe`.
